# Generated by Django 5.1.6 on 2025-02-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aiuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indata', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.openaichat')),
                ('procedure', models.ManyToManyField(to='api.testprocedure')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.testbattery')),
            ],
        ),
    ]
