# Generated by Django 5.1.6 on 2025-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_testprocedure_testbattery_testresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testbattery',
            options={'verbose_name_plural': 'Test batteries'},
        ),
        migrations.AddField(
            model_name='testbattery',
            name='expect',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testprocedure',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
