# Generated by Django 5.1.6 on 2025-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_testbattery_ddxtest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddxtest',
            options={},
        ),
        migrations.AlterField(
            model_name='ddxtest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
