# Generated by Django 5.1.6 on 2025-02-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ddxtestresult_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DDXTest',
            new_name='DDXTestCase',
        ),
        migrations.AlterField(
            model_name='ddxtestresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ddxtestrun'),
        ),
    ]
