# Generated by Django 5.1.6 on 2025-02-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_ddxtestrun_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaichat',
            name='messages',
        ),
        migrations.CreateModel(
            name='OpenAIChat_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('openaichat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.openaichat')),
                ('openaimessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.openaimessage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
