# Generated by Django 5.1.6 on 2025-02-17 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_openaichat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDXCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ddxtestcase')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.openaichat')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ddxtestrun')),
            ],
        ),
        migrations.CreateModel(
            name='DDXCaseResult_diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('ddxcaseresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ddxcaseresult')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.AddField(
            model_name='ddxcaseresult',
            name='diagnoses',
            field=models.ManyToManyField(through='api.DDXCaseResult_diagnoses', to='api.diagnosis'),
        ),
        migrations.DeleteModel(
            name='DDXTestResult',
        ),
    ]
