<script lang="ts">
import { useChat } from 'ai/svelte';
 
const { input, handleSubmit, messages, isLoading } = useChat({
  api: 'api/openai',
});

const content = {
  h1: "ChatDDx -  Differential diagnostic decision support tool for EM physicians",
  promptDescription: "Enter the patient's symtoms, background and findnings. Input in Swedish or English.",
  promptSubmit: "Generate differential diagnoses",
  responseTitle: "Differential diagnoses",
  usageOpen: "How to use",
  usageClose: "OK",
  usageText: `
#How to use
Enter pathological and clinically relevant patient information in the same manner as you would when consulting another EM specialist.
Example 1: Previously healthy patient who became ill with abdominal pain, fever, diarrhea, and vomiting after a 5-day cruise.
Status with reduced general condition, tachycardia, fever, and general abdominal pain. CRP 178, leukocytosis,
and blood gas with metabolic acidosis with hypokalemia and renal failure.
Example 2: A 64-year-old man with congestive heart failure and hypertension presenting with acute onset of retrosternal chest pain,
shortness of breath, and cold sweating. Elevated troponin but normal ECG.
Example 3: 27-year-old previously healthy woman with sudden onset of intermittent lower left quadrant abdominal pain with nausea and vomiting.
Normal CRP and blood work.
`,
  disclaimerOpen: "Disclaimer",
  disclaimerClose: "I understand",
  disclaimerText: `
#Disclaimer
This application utilizes GPT4 via API to generate potential differential diagnoses with the most probable diagnosis first
based on user-provided information. Do not provide personal data such as name or social security number.
It is crucial to understand that the information provided by this application is not a substitute for professional
medical advice, diagnosis, or treatment.
The generated differential diagnoses are algorithmically derived and should be considered as suggestions for further
exploration rather than definitive conclusions.
Users are strongly encouraged to consult with qualified healthcare professionals for accurate diagnosis and personalized medical advice.
The developers and providers of this application, as well as OpenAI, do not assume any liability for the accuracy,
completeness, or reliability of the information generated by this application.
Users should always exercise their own judgment and seek medical attention from qualified healthcare providers
when making medical diagnostic decisions.
By using this application, users acknowledge that it is not a replacement for professional medical expertise and
that the developers and providers are not responsible for any actions taken based on the information provided.
Copyright © 2023 ChatDDX
`,
};

$: assistantMessages = $messages.filter(m => m.role === 'assistant');

</script>

<section class="p-2 bg-orange-600 text-white">
<h1 class="text-3xl">{content.h1}</h1>
</section>
<section class="p-2 form-control max-w-full center container mx-auto leading-tight">
  <div class=" ">{content.promptDescription}</div>
  <label class="form-control center container mx-auto">
    <div class="label"></div>
    <form on:submit={handleSubmit}>
      <textarea
        id="user-prompt"
        rows="7"
        class="p-0 textarea textarea-primary textarea-md leading-tight"
        placeholder="Enter revelvant patient data"
        bind:value={$input}
      />
      <div class="flex py-2">
        <button
          id="query-button"
          class="btn btn-primary mr-4"
          type="submit"
          disabled={$isLoading}
        >{content.promptSubmit}</button>
        <span id="query-loading" class="loading loading-spinner loading-lg text-secondary" class:hidden={!$isLoading}></span>
      </div>
    </form>
    <modal>
      <button class="btn my-0.5 textarea-primary text-xs" onclick="my_modal_1.showModal()">{content.disclaimerOpen}</button>
  <dialog id="my_modal_1" class="modal ">  
    <div class="modal-box max-w-full">
      <p class="py-4"></p>
      <div class="modal-action">
        <form method="dialog">
          <button class="btn">{content.disclaimerClose}</button>
        </form>
      </div>
    </div>
  </dialog>

  <button class="btn my-2 textarea-primary text-xs " onclick="my_modal_2.showModal()">{content.usageOpen}</button>
  <dialog id="my_modal_2" class="modal">  
        {content.usageText}
          <button class="btn">{content.usageClose}</button>
  </dialog>
</modal>
  <div class="">{content.responseTitle}</div> 
    <pre
      id="user-response"
      class="whitespace-pre-wrap break-words center: true,max-w-prose bg-base-200 rounded-lg min-h-64 p-2"
    >{#if assistantMessages.length}{assistantMessages?.at(-1)?.content || ""}{/if}</pre>
</section>
