<script lang="ts">
  import { Container } from 'postcss';
import type { PageData } from './$types';
  import OpenAI from "openai";

  export let data: PageData;

  let client = new OpenAI({
    baseURL: data.oai.diagnoses.endpoint,
    apiKey: data.oai.diagnoses.api_key,
    dangerouslyAllowBrowser: true,
    fetch,
  });

  async function run({api_key, endpoint, identifier, ...payload}) {
    let content = document.getElementById('user-prompt').value.trim();
    let button = document.getElementById('query-button');
    let loading = document.getElementById('query-loading');
    let response = document.getElementById('response');

    let result;
    let messages = [...data.oai.diagnoses.messages, { content, role: "user" }];

    response.textContent = "";

    button.disabled = true;
    loading.classList.remove("hidden");

    try {
      result = await client.chat.completions.create({...payload, messages});
    } catch (error) {
      response.textContent = `Error fetching data from OpenAI: ${error.message}`;
      button.disabled = false;
      loading.classList.add("hidden");
      return;
    }

    if (data.oai.diagnoses.stream) {
      for await (const chunk of result) {
        response.textContent = response.textContent + (chunk.choices[0]?.delta?.content || "");
      }
    } else {
      response.textContent = (result.choices[0].message.content || "");
    }
    button.disabled = false;
    loading.classList.add("hidden");
  }

</script>

<section class="p-2 bg-orange-600 text-white">
<h1 class="text-3xl">
  ChatDDx -  Differential diagnostic decision support tool for EM physicians
</h1>
</section>
<section class="p-2 form-control max-w-full center container mx-auto leading-tight">
  <div class=" ">Enter the patient's symtoms, background and findnings. Input in Swedish or English.</div>
  <label class="form-control center container mx-auto">
    <div class="label">
    </div>
    <textarea
        id="user-prompt"
        rows="7"
        class="p-0 textarea textarea-primary textarea-md leading-tight"
        placeholder="Enter revelvant patient data"
        ></textarea>
        <modal Container >
         <button class="btn my-0.5 textarea-primary text-xs" onclick="my_modal_1.showModal()">Disclaimer</button>
  <dialog id="my_modal_1" class="modal ">  
    <div class="modal-box max-w-full">
      <h3 class="font text-med">  <table>
        <tr>
            <table>
                <tr>
                   
                <th>Disclaimer</th>
              </tr>
              <tr>
                  <td align="left">This application utilizes GPT4 via API to generate potential differential diagnoses with the most probable diagnosis first based on user-provided information. Do not provide personal data such as name or social security number.</td>
              </tr>
              <tr>
                  <td align="left">It is crucial to understand that the information provided by this application is not a substitute for professional medical advice, diagnosis, or treatment.</td>
              </tr>
              <tr>
                  <td align="left">The generated differential diagnoses are algorithmically derived and should be considered as suggestions for further exploration rather than definitive conclusions.</td>
              </tr>
              <tr>
                  <td align="left">Users are strongly encouraged to consult with qualified healthcare professionals for accurate diagnosis and personalized medical advice.</td>
              </tr>
              <tr>
                  <td align="left">The developers and providers of this application, as well as OpenAI, do not assume any liability for the accuracy, completeness, or reliability of the information generated by this application.</td>
              </tr>
              <tr>
                  <td align="left">Users should always exercise their own judgment and seek medical attention from qualified healthcare providers when making medical diagnostic decisions.</td>
              </tr>
              <tr>
                  <td align="left">By using this application, users acknowledge that it is not a replacement for professional medical expertise and that the developers and providers are not responsible for any actions taken based on the information provided.</td> 
              </tr>
              <tr>
                <td align="left">&nbsp;</td> <!-- Empty row for spacing -->
            </tr>
            <tr>
              <tr>
                  <td align="left">Copyright © 2023 ChatDDX</td>
  
                </tr>
            </table></h3>
      <p class="py-4"></p>
      <div class="modal-action">
        <form method="dialog">
          <button class="btn">I understand</button>
        </form>
      </div>
    </div>
  </dialog>

  <button class="btn my-2 textarea-primary text-xs " onclick="my_modal_2.showModal()">How to use ℹ️</button>
  <dialog id="my_modal_2" class="modal">  
    <div class="modal-box max-w-full ">
      <h3 class="font text-med">  <table>
        <tr>
          <table>
            <tr>
              <th>How to use</th>
            </tr>
            <tr>
              <td class="example" style="padding-bottom: 10px;">Enter pathological and clinically relevant patient information in the same manner as you would when consulting another EM specialist.</td>
            </tr>
            <tr>
              <td class="example" style="padding-bottom: 10px;">Example 1: Previously healthy patient who became ill with abdominal pain, fever, diarrhea, and vomiting after a 5-day cruise. Status with reduced general condition, tachycardia, fever, and general abdominal pain. CRP 178, leukocytosis, and blood gas with metabolic acidosis with hypokalemia and renal failure.</td>
            </tr>
            <tr>
              <td class="example" style="padding-bottom: 10px;">Example 2: A 64-year-old man with congestive heart failure and hypertension presenting with acute onset of retrosternal chest pain, shortness of breath, and cold sweating. Elevated troponin but normal ECG.</td>
            </tr>
            <tr>
              <td class="example" style="padding-bottom: 10px;">Example 3: 27-year-old previously healthy woman with sudden onset of intermittent lower left quadrant abdominal pain with nausea and vomiting. Normal CRP and blood work.</td> 
            </tr> 
          </table></h3>
      <p class="py-4"></p>
      <div class="modal-action">
        <form method="dialog">
          <button class="btn">OK </button>
        </form>
      </div>
    </div>
  </dialog>
</modal>
  <div class="flex py-2">
    <button id="query-button" class="btn btn-primary mr-4" on:click={()=>run(data.oai.diagnoses)}>Generate differential diagnoses</button>
    <span id="query-loading" class="loading loading-spinner loading-lg text-secondary hidden"></span>
  </div>
  <div class="">Differential diagnosis</div> 
  <pre id="response" class="whitespace-pre-wrap break-words center: true,max-w-prose bg-base-200 rounded-lg min-h-64 p-2"></pre>
</section>
