[tool.poetry]
name = "mysite"
version = "0.1.0"
description = ""
authors = [
	"Olof Silfver <olof.silfver@gmail.com>",
	"Alexander Holmbäck <alexander.holmback@gmail.com>",
]
readme = "README.md"

[tool.poetry.scripts]
setup = 'djrolf.setup:run'

[tool.poetry.dependencies]
python = "^3.11"
Django = "^5.0.1"
gunicorn = "^21.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
