# Generated by Django 4.2.7 on 2024-01-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='text',
            new_name='message',
        ),
        migrations.AddField(
            model_name='prompt',
            name='role',
            field=models.TextField(default=''),
        ),
    ]
