# Generated by Django 5.0.1 on 2024-01-25 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt", "0002_rename_text_prompt_message_prompt_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAILogitBias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "bias",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(-100),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenAIMessageRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OpenAIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OpenAIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gpt.openaimessagerole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenAIChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                (
                    "frequency_penalty",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2000),
                        ]
                    ),
                ),
                (
                    "presence_penalty",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.FloatField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                (
                    "logit_bias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gpt.openailogitbias",
                    ),
                ),
                ("messages", models.ManyToManyField(to="gpt.openaimessage")),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gpt.openaimodel",
                    ),
                ),
            ],
        ),
    ]
