# Generated by Django 5.0.1 on 2024-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt", "0003_openailogitbias_openaimessagerole_openaimodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openaichat",
            options={"verbose_name_plural": "OpenAI Chat Configuration"},
        ),
        migrations.AlterModelOptions(
            name="openailogitbias",
            options={"verbose_name_plural": "OpenAI Logit Biases"},
        ),
        migrations.AlterModelOptions(
            name="openaimessage",
            options={"verbose_name_plural": "OpenAI Messages"},
        ),
        migrations.AlterModelOptions(
            name="openaimessagerole",
            options={"verbose_name_plural": "OpenAI Message Roles"},
        ),
        migrations.AlterModelOptions(
            name="openaimodel",
            options={"verbose_name_plural": "OpenAI Models"},
        ),
        migrations.RenameField(
            model_name="openaimodel",
            old_name="endpoint",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="openaimessage",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
