# Generated by Django 5.0.1 on 2024-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt", "0005_alter_openaichat_logit_bias_alter_openaichat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaichat",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="openaimessage",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
