# Generated by Django 5.0.4 on 2024-04-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSAssistantView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_sv', models.CharField(max_length=255, null=True)),
                ('promptLabel', models.CharField(max_length=255)),
                ('promptLabel_en', models.CharField(max_length=255, null=True)),
                ('promptLabel_sv', models.CharField(max_length=255, null=True)),
                ('promptButton', models.CharField(max_length=255)),
                ('promptButton_en', models.CharField(max_length=255, null=True)),
                ('promptButton_sv', models.CharField(max_length=255, null=True)),
                ('responseLabel', models.CharField(max_length=255)),
                ('responseLabel_en', models.CharField(max_length=255, null=True)),
                ('responseLabel_sv', models.CharField(max_length=255, null=True)),
                ('usageOpen', models.CharField(max_length=255)),
                ('usageOpen_en', models.CharField(max_length=255, null=True)),
                ('usageOpen_sv', models.CharField(max_length=255, null=True)),
                ('usageClose', models.CharField(max_length=255)),
                ('usageClose_en', models.CharField(max_length=255, null=True)),
                ('usageClose_sv', models.CharField(max_length=255, null=True)),
                ('usageText', models.TextField()),
                ('usageText_en', models.TextField(null=True)),
                ('usageText_sv', models.TextField(null=True)),
                ('disclaimerOpen', models.CharField(max_length=255)),
                ('disclaimerOpen_en', models.CharField(max_length=255, null=True)),
                ('disclaimerOpen_sv', models.CharField(max_length=255, null=True)),
                ('disclaimerClose', models.CharField(max_length=255)),
                ('disclaimerClose_en', models.CharField(max_length=255, null=True)),
                ('disclaimerClose_sv', models.CharField(max_length=255, null=True)),
                ('disclaimerText', models.TextField()),
                ('disclaimerText_en', models.TextField(null=True)),
                ('disclaimerText_sv', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Content management for assistant view',
            },
        ),
    ]
