# Generated by Django 5.0.4 on 2024-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_cmsassistantview_assistantpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantpage',
            options={'verbose_name_plural': 'Assistant page'},
        ),
        migrations.AddField(
            model_name='assistantpage',
            name='promptPlaceholder',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
    ]
