# Generated by Django 6.0.5 on 2026-06-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_agent_connection_identity_message_outputtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superagent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='default_agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orm.agentbranchmodel'),
        ),
    ]
