# Generated by Django 6.0.5 on 2026-06-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_alter_superagent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent (simple)', 'verbose_name_plural': 'Agents (simple)'},
        ),
    ]
