# Generated by Django 6.0.5 on 2026-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_alter_agent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSession',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Session',
                'verbose_name_plural': 'Shared Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orm.sessionmodel',),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='collaborators',
            field=models.ManyToManyField(related_name='shared_sessions', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='kind',
            field=models.CharField(choices=[('request', 'Request'), ('response', 'Response'), ('error', 'Error'), ('prompt', 'Prompt')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
