# Generated by Django 6.0.5 on 2026-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_sharedsession_sessionmodel_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_sessions', to='orm.identitymodel'),
        ),
    ]
