# Generated by Django 6.0.5 on 2026-06-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_alter_sessionmodel_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputtypetrailmodel',
            name='output_retries',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('unknown', 'Unknown')], max_length=255),
        ),
    ]
