# Generated by Django 6.0.5 on 2026-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_outputtypetrailmodel_output_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbranchmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AddField(
            model_name='connectionbranchmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AddField(
            model_name='outputtypebranchmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AddField(
            model_name='samplingparamsbranchmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AddField(
            model_name='toolbranchmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AddField(
            model_name='toolgroupbranchmodel',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel'),
        ),
    ]
