# Generated by Django 6.0.5 on 2026-07-22 16:29

import chatddx.repo.base
import chatddx.repo.proxies
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_agentbranchmodel_collaborators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAgent',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Agent (simple)',
                'verbose_name_plural': 'Shared Agents (simple)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.base.BranchProxy, 'orm.agentbranchmodel', chatddx.repo.proxies.Shared),
        ),
        migrations.CreateModel(
            name='SharedSuperAgent',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Agent',
                'verbose_name_plural': 'Shared Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.base.BranchProxy, 'orm.agentbranchmodel', chatddx.repo.proxies.Shared),
        ),
    ]
