# Generated by Django 5.0.4 on 2024-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_assistantpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantpage',
            name='promptPlaceholder_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assistantpage',
            name='promptPlaceholder_sv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
