# Generated by Django 6.0.2 on 2026-05-11 13:51

import uuid

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models

import chatddx_backend.agents.admin.proxies
import chatddx_backend.agents.models.agent
import chatddx_backend.agents.trail.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("instructions", models.TextField()),
            ],
            options={
                "db_table": "agents_agent",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("ollama", "Ollama"),
                            ("vllm", "vLLM"),
                        ],
                        max_length=255,
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("endpoint", models.URLField(max_length=2048)),
                ("profile", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agents_connection",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    chatddx_backend.agents.models.agent.JSONSchemaField(default=dict),
                ),
                (
                    "validation_strategy",
                    models.CharField(
                        choices=[
                            ("noop", "Noop"),
                            ("retry", "Retry"),
                            ("inform", "Inform"),
                            ("crash", "Crash"),
                        ],
                        default="inform",
                        max_length=255,
                    ),
                ),
                (
                    "coercion_strategy",
                    models.CharField(
                        choices=[
                            ("prompted", "Prompted"),
                            ("tool", "Tool"),
                            ("native", "Native"),
                        ],
                        default="native",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "agents_output_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SamplingParamsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("seed", models.IntegerField(blank=True, default=None, null=True)),
                ("n", models.PositiveIntegerField(blank=True, default=None, null=True)),
                (
                    "presence_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "frequency_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "logit_bias",
                    models.JSONField(
                        blank=True,
                        decoder=chatddx_backend.agents.models.agent.DecimalDecoder,
                        default=dict,
                        encoder=chatddx_backend.agents.models.agent.DecimalEncoder,
                    ),
                ),
                ("provider_params", models.JSONField(blank=True, default=dict)),
                (
                    "stop_sequences",
                    models.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "agents_sampling_params",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolGroupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("instructions", models.TextField()),
                (
                    "tools",
                    chatddx_backend.agents.trail.models.RelatedArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        associated_model=chatddx_backend.agents.models.agent.ToolModel,
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_group",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the tool", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("code_interpreter", "Code Interpreter"),
                            ("file_search", "File Search"),
                            ("web_search", "Web Search"),
                        ],
                        default="function",
                        help_text="The type of tool.",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("parameters", chatddx_backend.agents.models.agent.JSONSchemaField()),
            ],
            options={
                "db_table": "agents_tool",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx_backend.agents.admin.proxies.TrailProxy,
                "agents.agentmodel",
            ),
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="agents.connectionmodel"
            ),
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx_backend.agents.admin.proxies.TrailProxy,
                "agents.connectionmodel",
            ),
        ),
        migrations.CreateModel(
            name="IdentityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("secrets", encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ("guest_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_identity",
            },
        ),
        migrations.CreateModel(
            name="AgentBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="agents.agentmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[],
            options={
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("agents.identitymodel",),
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("request", "Request"), ("response", "Response")],
                        max_length=255,
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.agentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_message",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("agents.messagemodel",),
        ),
        migrations.CreateModel(
            name="OutputTypeBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="agents.outputtypemodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_output_type_branch",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="output_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="agents.outputtypemodel"
            ),
        ),
        migrations.CreateModel(
            name="OutputType",
            fields=[],
            options={
                "verbose_name": "Output type",
                "verbose_name_plural": "Output types",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx_backend.agents.admin.proxies.TrailProxy,
                "agents.outputtypemodel",
            ),
        ),
        migrations.CreateModel(
            name="SamplingParamsBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="agents.samplingparamsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_sampling_params_branch",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="sampling_params",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="agents.samplingparamsmodel",
            ),
        ),
        migrations.CreateModel(
            name="SamplingParams",
            fields=[],
            options={
                "verbose_name": "Sampling parameters",
                "verbose_name_plural": "Sampling parameters",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx_backend.agents.admin.proxies.TrailProxy,
                "agents.samplingparamsmodel",
            ),
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "default_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.agentbranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_session",
            },
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="agents.sessionmodel",
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("agents.sessionmodel",),
        ),
        migrations.CreateModel(
            name="ToolGroupBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="agents.toolgroupmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_group_branch",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="tool_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="agents.toolgroupmodel"
            ),
        ),
        migrations.CreateModel(
            name="ToolGroup",
            fields=[],
            options={
                "verbose_name": "Tool group",
                "verbose_name_plural": "Tool groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx_backend.agents.admin.proxies.TrailProxy,
                "agents.toolgroupmodel",
            ),
        ),
        migrations.CreateModel(
            name="ToolBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="agents.toolmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(chatddx_backend.agents.admin.proxies.TrailProxy, "agents.toolmodel"),
        ),
        migrations.CreateModel(
            name="ConnectionBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="agents.connectionmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_connection_branch",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "name", "-timestamp"],
                        name="agents_conn_owner_i_3a81d6_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_agen_owner_i_c9688a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputtypebranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_outp_owner_i_8e4c40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samplingparamsbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_samp_owner_i_1f8b1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolgroupbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_tool_owner_i_384545_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_tool_owner_i_e1f0a7_idx",
            ),
        ),
    ]
