# Generated by Django 6.0.2 on 2026-05-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolmodel',
            old_name='name',
            new_name='command',
        ),
    ]
