# Generated by Django 6.0.2 on 2026-05-15 17:51

import chatddx_backend.agents.admin.proxies
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_name_toolmodel_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAgent',
            fields=[
            ],
            options={
                'verbose_name': 'Super Agent',
                'verbose_name_plural': 'Super Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx_backend.agents.admin.proxies.TrailProxy, 'agents.agentbranchmodel'),
        ),
    ]
