# Generated by Django 6.0.2 on 2026-03-30 19:00

import uuid

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models

import chatddx_backend.agents.models.agent
import chatddx_backend.agents.trail.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for this record, last update is considered canon.",
                        max_length=255,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Fingerprint for this configuration",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("ollama", "Ollama"),
                            ("vllm", "vLLM"),
                        ],
                        max_length=255,
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("endpoint", models.URLField(max_length=2048)),
                (
                    "profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model-specific profile parameters fed to pydantic-ai's ModelProfile",
                    ),
                ),
            ],
            options={
                "db_table": "agents_connection",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="agents_conn_name_c1cff2_idx")
                ],
                "unique_together": {("name", "fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="IdentityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("secrets", encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ("guest_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_identity",
            },
        ),
        migrations.CreateModel(
            name="OutputTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for this record, last update is considered canon.",
                        max_length=255,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Fingerprint for this configuration",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    chatddx_backend.agents.models.agent.JSONSchemaField(
                        help_text="A valid JSON Schema defining the expected agent response structure."
                    ),
                ),
            ],
            options={
                "db_table": "agents_output_type",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="agents_outp_name_14b7c8_idx")
                ],
                "unique_together": {("name", "fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="SamplingParamsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for this record, last update is considered canon.",
                        max_length=255,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Fingerprint for this configuration",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Controls randomness in responses; higher values (>1.0) increase creativity, lower values make output more deterministic.",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Nucleus sampling threshold; the model considers tokens with cumulative probability up to this value (e.g., 0.9 means top 90% probable tokens).",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Limits sampling to the k most likely next tokens (e.g., 40 means only consider the top 40 tokens).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Maximum number of tokens to generate in the response.",
                        null=True,
                    ),
                ),
                (
                    "seed",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Random seed for deterministic output; using the same seed with identical inputs produces consistent results.",
                        null=True,
                    ),
                ),
                (
                    "n",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Number of response variations to generate for each prompt.",
                        null=True,
                    ),
                ),
                (
                    "presence_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Penalty for using tokens that have already appeared, encouraging the model to introduce new topics (typically -2.0 to 2.0).",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "frequency_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Penalty based on how often tokens appear, reducing repetition (typically -2.0 to 2.0).",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "logit_bias",
                    models.JSONField(
                        blank=True,
                        decoder=chatddx_backend.agents.models.agent.DecimalDecoder,
                        default=dict,
                        encoder=chatddx_backend.agents.models.agent.DecimalEncoder,
                        help_text="Adjusts likelihood of specific tokens appearing in the output.\nExamples: {'50256': -100} (suppress token), {'12345': 10, '67890': 5} (boost tokens)",
                    ),
                ),
                (
                    "provider_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Provider-specific parameters not covered by standard fields.\nExamples: {"response_format": {"type": "json_object"}}, {"anthropic_version": "2023-06-01", "thinking": {"type": "enabled"}}',
                    ),
                ),
                (
                    "stop_sequences",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text='List of strings that will stop generation when encountered.\nExamples: ["\\n\\n", "END"], ["\\"\\"\\""]',
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "agents_sampling_params",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="agents_samp_name_54aa46_idx")
                ],
                "unique_together": {("name", "fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="AgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for this record, last update is considered canon.",
                        max_length=255,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Fingerprint for this configuration",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("instructions", models.TextField()),
                (
                    "validation_strategy",
                    models.CharField(
                        choices=[
                            ("noop", "Noop"),
                            ("retry", "Retry"),
                            ("inform", "Inform"),
                            ("crash", "Crash"),
                        ],
                        default="inform",
                        max_length=255,
                    ),
                ),
                (
                    "coercion_strategy",
                    models.CharField(
                        choices=[
                            ("prompted", "Prompted"),
                            ("tool", "Tool"),
                            ("native", "Native"),
                        ],
                        default="native",
                        max_length=255,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.connectionmodel",
                    ),
                ),
                (
                    "output_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.outputtypemodel",
                    ),
                ),
                (
                    "sampling_params",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.samplingparamsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "default_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.agentmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_session",
            },
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("request", "Request"), ("response", "Response")],
                        max_length=255,
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.agentmodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="agents.sessionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_message",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ToolGroupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for this record, last update is considered canon.",
                        max_length=255,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Fingerprint for this configuration",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("instructions", models.TextField()),
                (
                    "tools",
                    chatddx_backend.agents.trail.models.RelatedArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        help_text="Snapshot of tool pks attached to this configuration version.",
                        related_model=chatddx_backend.agents.models.agent.ToolModel,
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_group",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="agents_tool_name_664592_idx")
                ],
                "unique_together": {("name", "fingerprint")},
            },
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="tool_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="agents.toolgroupmodel"
            ),
        ),
        migrations.CreateModel(
            name="ToolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for this record, last update is considered canon.",
                        max_length=255,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Fingerprint for this configuration",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("code_interpreter", "Code Interpreter"),
                            ("file_search", "File Search"),
                            ("web_search", "Web Search"),
                        ],
                        default="function",
                        help_text="The type of tool.",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "parameters",
                    chatddx_backend.agents.models.agent.JSONSchemaField(
                        blank=True,
                        default=None,
                        help_text='JSON Schema describing the tool\'s parameters.\nExample: {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}',
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="agents_tool_name_43a15c_idx")
                ],
                "unique_together": {("name", "fingerprint")},
            },
        ),
        migrations.AddIndex(
            model_name="agentmodel",
            index=models.Index(fields=["name"], name="agents_agen_name_26b7c8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="agentmodel",
            unique_together={("name", "fingerprint")},
        ),
    ]
