# Generated by Django 6.0.2 on 2026-03-13 15:11

import chatddx_backend.agents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Fingerprint for this configuration', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier for this configuration.', max_length=255, unique=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Controls randomness in responses; higher values (>1.0) increase creativity, lower values make output more deterministic.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('top_p', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Nucleus sampling threshold; the model considers tokens with cumulative probability up to this value (e.g., 0.9 means top 90% probable tokens).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('top_k', models.IntegerField(blank=True, default=None, help_text='Limits sampling to the k most likely next tokens (e.g., 40 means only consider the top 40 tokens).', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_tokens', models.PositiveIntegerField(blank=True, default=None, help_text='Maximum number of tokens to generate in the response.', null=True)),
                ('seed', models.IntegerField(blank=True, default=None, help_text='Random seed for deterministic output; using the same seed with identical inputs produces consistent results.', null=True)),
                ('n', models.PositiveIntegerField(blank=True, default=None, help_text='Number of response variations to generate for each prompt.', null=True)),
                ('presence_penalty', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Penalty for using tokens that have already appeared, encouraging the model to introduce new topics (typically -2.0 to 2.0).', max_digits=3, null=True)),
                ('frequency_penalty', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Penalty based on how often tokens appear, reducing repetition (typically -2.0 to 2.0).', max_digits=3, null=True)),
                ('stop_sequences', models.JSONField(blank=True, default=None, help_text='List of strings that will stop generation when encountered.\nExamples: ["\\n\\n", "END"], ["\\"\\"\\""]', null=True)),
                ('logit_bias', models.JSONField(blank=True, default=None, help_text="Adjusts likelihood of specific tokens appearing in the output.\nExamples: {'50256': -100} (suppress token), {'12345': 10, '67890': 5} (boost tokens)", null=True)),
                ('provider_params', models.JSONField(blank=True, default=None, help_text='Provider-specific parameters not covered by standard fields.\nExamples: {"response_format": {"type": "json_object"}}, {"anthropic_version": "2023-06-01", "thinking": {"type": "enabled"}}', null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
                'indexes': [models.Index(fields=['name', '-updated_at'], name='agents_conf_name_a30017_idx')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Fingerprint for this configuration', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier for this connection.', max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'Openai'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('ollama', 'Ollama'), ('vllm', 'Vllm')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('endpoint', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
                'indexes': [models.Index(fields=['name', '-updated_at'], name='agents_conn_name_5476e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Fingerprint for this configuration', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier for this schema.', max_length=255, unique=True)),
                ('definition', models.JSONField(help_text='A valid JSON Schema defining the expected agent response structure.', validators=[chatddx_backend.agents.models.validate_json_schema])),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
                'indexes': [models.Index(fields=['name', '-updated_at'], name='agents_sche_name_2341f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Fingerprint for this configuration', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('instructions', models.TextField()),
                ('use_tools', models.BooleanField(default=False)),
                ('validation_strategy', models.CharField(choices=[('none', 'None'), ('retry', 'Retry'), ('inform', 'Inform'), ('crash', 'Crash')], default='inform', max_length=255)),
                ('coercion_strategy', models.CharField(blank=True, choices=[('prompted', 'Prompted'), ('tool', 'Tool'), ('native', 'Native')], default=None, max_length=255, null=True)),
                ('config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agents', to='agents.config')),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agents', to='agents.connection')),
                ('schema', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agents', to='agents.schema')),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='agents.agent')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=255)),
                ('run_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.session')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Fingerprint for this configuration', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier for this tool.', max_length=255, unique=True)),
                ('type', models.CharField(choices=[('function', 'Function'), ('code_interpreter', 'Code Interpreter'), ('file_search', 'File Search'), ('web_search', 'Web Search')], default='function', help_text='The type of tool.', max_length=50)),
                ('parameters', models.JSONField(blank=True, default=None, help_text='JSON Schema describing the tool\'s parameters.\nExample: {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}', null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
                'indexes': [models.Index(fields=['name', '-updated_at'], name='agents_tool_name_9a2559_idx')],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, to='agents.tool'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['name', '-updated_at'], name='agents_agen_name_328854_idx'),
        ),
    ]
