# Generated by Django 6.0.2 on 2026-02-24 00:13

import chatddx_backend.agents.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this configuration.', max_length=255, unique=True)),
                ('temperature', models.FloatField(blank=True, default=None, help_text='Controls randomness in responses; higher values (>1.0) increase creativity, lower values make output more deterministic.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('top_p', models.FloatField(blank=True, default=None, help_text='Nucleus sampling threshold; the model considers tokens with cumulative probability up to this value (e.g., 0.9 means top 90% probable tokens).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('top_k', models.IntegerField(blank=True, default=None, help_text='Limits sampling to the k most likely next tokens (e.g., 40 means only consider the top 40 tokens).', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_tokens', models.PositiveIntegerField(blank=True, default=None, help_text='Maximum number of tokens to generate in the response.', null=True)),
                ('seed', models.IntegerField(blank=True, default=None, help_text='Random seed for deterministic output; using the same seed with identical inputs produces consistent results.', null=True)),
                ('n', models.PositiveIntegerField(blank=True, default=None, help_text='Number of response variations to generate for each prompt.', null=True)),
                ('presence_penalty', models.FloatField(blank=True, default=None, help_text='Penalty for using tokens that have already appeared, encouraging the model to introduce new topics (typically -2.0 to 2.0).', null=True)),
                ('frequency_penalty', models.FloatField(blank=True, default=None, help_text='Penalty based on how often tokens appear, reducing repetition (typically -2.0 to 2.0).', null=True)),
                ('stop_sequences', models.JSONField(blank=True, default=list, help_text='List of strings that will stop generation when encountered.\nExamples: ["\\n\\n", "END"], ["\\"\\"\\""]')),
                ('logit_bias', models.JSONField(blank=True, default=dict, help_text="Adjusts likelihood of specific tokens appearing in the output.\nExamples: {'50256': -100} (suppress token), {'12345': 10, '67890': 5} (boost tokens)")),
                ('provider_params', models.JSONField(blank=True, default=dict, help_text='Provider-specific parameters not covered by standard fields.\nExamples: {"response_format": {"type": "json_object"}}, {"anthropic_version": "2023-06-01", "thinking": {"type": "enabled"}}')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'Openai'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('ollama', 'Ollama'), ('vllm', 'Vllm')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('endpoint', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this schema.', max_length=255, unique=True)),
                ('definition', models.JSONField(help_text='A valid JSON Schema defining the expected agent response structure.', validators=[chatddx_backend.agents.models.validate_json_schema])),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this tool.', max_length=255, unique=True)),
                ('type', models.CharField(choices=[('function', 'Function'), ('code_interpreter', 'Code Interpreter'), ('file_search', 'File Search'), ('web_search', 'Web Search')], default='function', help_text='The type of tool.', max_length=50)),
                ('parameters', models.JSONField(help_text='JSON Schema describing the tool\'s parameters.\nExample: {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('instructions', models.TextField()),
                ('validation_strategy', models.CharField(choices=[('retry', 'Retry'), ('inform', 'Inform'), ('crash', 'Crash')], default='inform', max_length=255)),
                ('tool_choice', models.JSONField(blank=True, default=None, null=True)),
                ('config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agents', to='agents.config')),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agents', to='agents.connection')),
                ('schema', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agents', to='agents.schema')),
                ('tools', models.ManyToManyField(blank=True, to='agents.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('developer', 'Developer'), ('thought', 'Thought'), ('reasoning', 'Reasoning')], max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.session')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('session', 'sequence')},
            },
        ),
    ]
