# Generated by Django 6.0.2 on 2026-03-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.agentmodel',),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.connectionmodel',),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.identitymodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.messagemodel',),
        ),
        migrations.CreateModel(
            name='OutputType',
            fields=[
            ],
            options={
                'verbose_name': 'Output Type',
                'verbose_name_plural': 'Output Types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.outputtypemodel',),
        ),
        migrations.CreateModel(
            name='SamplingParams',
            fields=[
            ],
            options={
                'verbose_name': 'Sampling Params',
                'verbose_name_plural': 'Sampling Params',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.samplingparamsmodel',),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.sessionmodel',),
        ),
        migrations.CreateModel(
            name='ToolGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Tool Group',
                'verbose_name_plural': 'Tool Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agents.toolgroupmodel',),
        ),
    ]
