# Generated by Django 6.0.2 on 2026-04-03 17:46

import chatddx_backend.agents.models.agent
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_connection_identity_message_outputtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputtype',
            options={'verbose_name': 'Output type', 'verbose_name_plural': 'Output types'},
        ),
        migrations.AlterModelOptions(
            name='samplingparams',
            options={'verbose_name': 'Sampling parameters', 'verbose_name_plural': 'Sampling parameters'},
        ),
        migrations.AlterModelOptions(
            name='toolgroup',
            options={'verbose_name': 'Tool group', 'verbose_name_plural': 'Tool groups'},
        ),
        migrations.AlterField(
            model_name='toolmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toolmodel',
            name='parameters',
            field=chatddx_backend.agents.models.agent.JSONSchemaField(help_text='JSON Schema describing the tool\'s parameters.\nExample: {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}'),
        ),
    ]
