# Generated by Django 6.0.2 on 2026-04-06 10:37

import chatddx_backend.agents.models.agent
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_outputtype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmodel',
            name='coercion_strategy',
        ),
        migrations.RemoveField(
            model_name='agentmodel',
            name='validation_strategy',
        ),
        migrations.AddField(
            model_name='outputtypemodel',
            name='coercion_strategy',
            field=models.CharField(choices=[('prompted', 'Prompted'), ('tool', 'Tool'), ('native', 'Native')], default='native', max_length=255),
        ),
        migrations.AddField(
            model_name='outputtypemodel',
            name='validation_strategy',
            field=models.CharField(choices=[('noop', 'Noop'), ('retry', 'Retry'), ('inform', 'Inform'), ('crash', 'Crash')], default='inform', max_length=255),
        ),
        migrations.AlterField(
            model_name='outputtypemodel',
            name='definition',
            field=chatddx_backend.agents.models.agent.JSONSchemaField(default=dict, help_text='A valid JSON Schema defining the expected agent response structure.'),
        ),
    ]
