# Generated by Django 5.0.4 on 2024-04-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CMSAssistantView',
            new_name='AssistantPage',
        ),
        migrations.AlterModelOptions(
            name='assistantpage',
            options={'verbose_name_plural': 'Content management for assistant page'},
        ),
    ]
