# Generated by Django 5.0.4 on 2024-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_assistantpage_promptplaceholder_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantpage',
            name='copyButton',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantpage',
            name='copyButton_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assistantpage',
            name='copyButton_sv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
