# Generated by Django 5.0.4 on 2024-04-23 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_prompthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompthistory',
            options={'verbose_name_plural': 'Prompt history'},
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
