# Generated by Django 5.1.6 on 2025-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_testbattery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbattery',
            name='procedure',
        ),
        migrations.RenameField(
            model_name='testbattery',
            old_name='indata',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='length',
            new_name='expect_pos',
        ),
        migrations.RemoveField(
            model_name='testbattery',
            name='model',
        ),
        migrations.AddField(
            model_name='testbattery',
            name='models',
            field=models.ManyToManyField(to='api.openaichat'),
        ),
        migrations.DeleteModel(
            name='TestProcedure',
        ),
    ]
