# Generated by Django 5.1.6 on 2025-02-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_testbattery_procedure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestBattery',
            new_name='DDXTest',
        ),
        migrations.RenameModel(
            old_name='TestResult',
            new_name='DDXTestResult',
        ),
    ]
