# Generated by Django 5.1.6 on 2025-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_ddxtestcase_name_alter_ddxtestgroup_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.RemoveField(
            model_name='ddxtestcase',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='ddxtestcase',
            name='diagnoses',
            field=models.ManyToManyField(to='api.diagnosis'),
        ),
    ]
