# Generated by Django 5.1.6 on 2025-02-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_diagnosis_options_remove_ddxtestcase_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddxtestrun',
            name='chat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.openaichat'),
            preserve_default=False,
        ),
    ]
