# Generated by Django 5.1.6 on 2025-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_ddxtestrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddxtestrun',
            name='snapshot',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
