# Generated by Django 5.1.6 on 2025-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_testbattery_options_testbattery_expect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbattery',
            name='name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
