# Generated by Django 5.1.6 on 2025-02-08 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ddxtest_options_alter_ddxtest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDXTestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ddxtestresult',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DDXTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ddxtestgroup')),
            ],
        ),
        migrations.AddField(
            model_name='ddxtestresult',
            name='run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.ddxtestrun'),
            preserve_default=False,
        ),
    ]
