# Generated by Django 5.1.6 on 2025-02-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ddxtestgroup_ddxtestresult_output_ddxtestrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddxtest',
            name='groups',
            field=models.ManyToManyField(to='api.ddxtestgroup'),
        ),
    ]
