# Generated by Django 5.1.6 on 2025-02-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ddxtest_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddxtest',
            old_name='models',
            new_name='chats',
        ),
    ]
