# Generated by Django 5.1.6 on 2025-02-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_models_ddxtest_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddxtestresult',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.openaichat'),
            preserve_default=False,
        ),
    ]
