# Generated by Django 5.1.6 on 2025-02-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_ddxtest_ddxtestcase_alter_ddxtestresult_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ddxtestcase',
            name='chats',
        ),
        migrations.AddField(
            model_name='ddxtestcase',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.diagnosis'),
        ),
    ]
