# Generated by Django 5.1.6 on 2025-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_diagnosis_remove_ddxtestcase_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddxtestcase',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ddxtestgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pattern',
            field=models.CharField(max_length=255),
        ),
    ]
