# Generated by Django 5.1.6 on 2025-02-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_openaichat_messages_openaichat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaichat',
            name='messages',
            field=models.ManyToManyField(through='api.OpenAIChat_messages', to='api.openaimessage'),
        ),
    ]
