# Generated by Django 5.1.6 on 2025-02-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_ddxcaseresult_ddxcaseresult_diagnoses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddxcaseresult',
            name='chat',
        ),
    ]
