# Generated by Django 5.1.6 on 2025-02-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_ddxcaseresult_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddxcaseresult_diagnoses',
            options={'ordering': ['rank']},
        ),
        migrations.RenameField(
            model_name='ddxcaseresult_diagnoses',
            old_name='score',
            new_name='rank',
        ),
    ]
