# Generated by Django 5.1.6 on 2025-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_ddxcaseresult_diagnoses_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddxtestcase',
            name='expect',
        ),
    ]
