# Generated by Django 5.1.6 on 2025-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_ddxtestcase_expect'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddxtestrun',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('failed', 'Failed'), ('completed', 'Completed')], default='not_started', max_length=12),
        ),
    ]
