# Generated by Django 5.1.6 on 2025-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ddxtestrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddxtestrun',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('failed', 'Failed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=12),
        ),
    ]
